const products = [
  {
    _id: '1',
    name: 'Aston martin DB12',
    image: '/images/astonmartin.jpeg',
    description:'DB12. Redefining and reinventing what it means to be a tourer. An icon risen from 73 years of category defining marvels. Cutting through continents, bruising benchmarks and taming tradition. DB12 reaches new heights of driver connection, performance and dynamic supremacy.This is no mere GT.',
    brand: 'Aston martin',
    category: 'Cars',
    price: 289000,
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Mercedes Benz AMG GT',
    image: '/images/mercedesbenz.jpg',
    description:'The all-new Mercedes-AMG GT Coupé breathes high performance, technical leadership, supreme appeal and absolute luxury. Its both motorsport thrill and everyday practicality all at once. Is that unexpected? No its exactly the vehicle youve been waiting for',
    brand: 'Mercedes Benz',
    category: 'Cars',
    price: 195990,
    countInStock: 3,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'BMW I7',
    image: '/images/bmw.jpg',
    description:'The fully electric BMW i7 combines electric performance and multisensory entertainment to produce an unforgettable motoring experience.',
    brand: 'Bmw',
    category: 'Cars',
    price: 222929,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Ferrari F8 Tributo',
    image: '/images/ferrari.jpg',
    description:'The Ferrari F8 Tributo is the new mid-rear-engined sports car that represents the highest expression of the Prancing Horse’s classic two-seater berlinetta. It is a car with unique characteristics and, as its name implies, is an homage to the most powerful V8 in Ferrari history.',
    brand: 'Ferrari',
    category: 'Cars',
    price: 199399,
    countInStock: 9,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Porche 911 GT3',
    image: '/images/porche.jpeg',
    description:
      'Anyone who dreams of a Porsche usually has an image in their mind: the 911 has been the epitome of an exciting, powerful sports car with day-to-day usability for 60 years.',
    brand: 'Porche',
    category: 'Cars',
    price: 249999,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Lamborghini Aventador',
    image: '/images/lamborghini.jpg',
    description:'DESIGNED TO PUSH BEYOND PERFORMANCE Revolutionary thinking is at the heart of every idea from Automobili Lamborghini. Whether it is aerospace inspired design or technologies applied to the naturally aspirated V12 engine or carbon fiber structure going beyond accepted limits is part of our philosophy.',
    brand: 'Lamborghini',
    category: 'Cars',
    price: 185999,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
]

export default products
